name: Sync Sourceforge to GitHub
on:
  workflow_dispatch:
jobs:
  mirror-sf-to-gh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: "saga-gis/saga-gis"
        path: saga-gis-gh
        fetch-depth: 0
        lfs: true
        submodules: true
    - run: |
        ls -la
        pwd
    # - run: git clone --mirror git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    # - run: git clone --depth 1 git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    # - run: git clone --mirror git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    - run: git clone --mirror --reference-if-able saga-gis-gh --dissociate --progress --verbose git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    - run: ls -la
    # - run: cd saga-gis-code.git
    - run: |
        ls -la
        ## git status
        git log -18
      working-directory: saga-gis-code.git
    # - run: |
    #     git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/echoix/saga-gis.git"
    #     git push --mirror github
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/echoix/saga-gis.git"
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.PAT }}
      working-directory: saga-gis-code.git
    #- run: git push --mirror --atomic --verbose --progress github
    #  working-directory: saga-gis-code.git
    - run: git push --mirror --atomic --verbose --progress --force-with-lease github
      working-directory: saga-gis-code.git
