name: Sync Sourceforge to GitHub
on:
  workflow_dispatch:
jobs:
  sync-sf-to-gh:
    runs-on: ubuntu-latest
    steps:
    # - run: git clone --mirror git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    # - run: git clone --depth 1 git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    - run: git clone --depth 1 --mirror git://git.code.sf.net/p/saga-gis/code saga-gis-code.git
    - run: ls -la
    # - run: cd saga-gis-code.git
    - run: ls -la
      working-directory: saga-gis-code.git
    # - run: |
    #     git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/echoix/saga-gis.git"
    #     git push --mirror github
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/echoix/saga-gis.git"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: saga-gis-code.git
    - run: git push --mirror github
      working-directory: saga-gis-code.git
